<a href="https://colab.research.google.com/github/x1001000/Python_snippets/blob/master/binomial_one_trial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html

In [ ]:
import numpy as np

length = 30
pA = 0.2

A = (np.random.sample(length) * 10).astype(int)
B = (np.random.sample(length) * 10).astype(int)

coA = np.random.binomial(1, pA, size=length)
coB = np.array([1] * length) - coA

print(A)
print(B)
print(A * coA + B * coB)

[7 5 3 1 2 3 4 2 6 9 4 7 7 5 7 9 2 1 7 9 1 6 4 7 5 4 4 5 4 9]
[4 2 9 6 6 8 3 0 4 7 2 5 2 5 5 9 5 8 2 4 5 5 4 2 3 9 1 9 5 7]
[4 5 9 6 6 8 3 0 4 7 2 7 2 5 5 9 5 8 7 4 5 5 4 2 3 4 4 9 5 7]
